import uuid
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from app.web_builder.Recommendation.app.services.groq_service import groq_service
from app.web_builder.Recommendation.app.services.template_question_generator import (
    TemplateQuestionGenerator,
    AnswerToPropsMapper,
)
from app.web_builder.Recommendation.app.crud.crud import (
    delete_session,
    get_session,
    save_metadata,
    save_session,
)

MAX_QUESTIONS = 10


def _normalize_question_text(text: Optional[str]) -> Optional[str]:
    if not text:
        return None
    return " ".join(text.strip().lower().split())


def _generate_unique_session_id(prefix: str = "sess_", short_attempts: int = 5) -> str:
    """
    Generate a session ID that is not already present in Redis.
    Try shortened UUIDs first for readability, then fall back to full UUIDs.
    """
    for _ in range(short_attempts):
        session_id = f"{prefix}{uuid.uuid4().hex[:8]}"
        if not get_session(session_id):
            return session_id

    while True:
        session_id = f"{prefix}{uuid.uuid4().hex}"
        if not get_session(session_id):
            return session_id


def start_session(user, data):
    # Extract user ID from User object
    user_id = user.user_id if hasattr(user, 'user_id') else user
    session_id = _generate_unique_session_id()

    requested_language = (data.language or "").strip()
    target_language = groq_service.normalize_language(requested_language, None)

    # Analyze business type from user prompt
    business_type = groq_service.analyze_business_type(data.prompt)

    session_data = {
        "user_id": user_id,
        "prompt": data.prompt,
        "language": target_language,
        "business_type": business_type,
        "answers": {},
        "question_history": [],
        "questions": [],
        "asked_questions": [],
        "asked_topics": [],
        "max_questions": MAX_QUESTIONS,
        "completed": False,
    }

    first_question = _generate_next_question(session_data)
    if not first_question:
        raise ValueError("Unable to generate interview questions.")

    save_session(session_id, session_data)

    # Return a list for backward compatibility, but only the first question is generated now.
    return session_id, [first_question]


def finalize_session(user, session_id, selected_features, project_id):
    # Extract user ID from User object
    user_id = user.user_id if hasattr(user, 'user_id') else user
    username = getattr(user, 'username', 'anonymous')
    
    # Get session data
    session = get_session(session_id)
    if not session:
        raise ValueError("Session not found")
    
    # First, ensure the project exists in the database
    from app.Auth.models.project import Project
    from app.Auth.db.session import SessionLocal
    
    db = SessionLocal()
    try:
        # Convert project_id to string for folder path operations
        project_id_str = str(project_id)
        
        # Try to get the project by project_id
        project = db.query(Project).filter(Project.project_id == project_id).first()
        
        # If project doesn't exist, create it
        if not project:
            from app.web_builder.Web_generator.app.utils.file_utils import ensure_project_dir
            
            # Create a new project
            project = Project(
                user_id=int(user_id) if isinstance(user_id, str) else user_id,
                project_name=f"Project {project_id_str[:8]}",
                folder_path=ensure_project_dir(project_id_str, db)
            )
            
            db.add(project)
            db.commit()
            db.refresh(project)
            
            # Update the project_id with the actual database ID
            project_id = project.project_id
    except Exception as e:
        db.rollback()
        print(f"Error ensuring project exists: {e}")
        raise
    finally:
        db.close()
    
    # Clean up session data
    clean_session = {k: v for k, v in session.items() if not k.startswith('_')}
    
    # Get ALL features from session (generated by AI)
    all_features = session.get('features', [])
    
    # Filter to only STICKLY SELECTED features
    # selected_features is a list of feature IDs from the selection screen
    features_to_save = []
    
    if selected_features:
        features_to_save = [
            f for f in all_features 
            if f.get("id") in selected_features
        ]
        print(f"[finalize_session] 🎯 Strictly filtered to {len(features_to_save)} SELECTED features")
    
    # Fallback 1: Check session level selected_features (if already saved via /select_features)
    if not features_to_save:
        saved_selection = session.get("selected_features", [])
        if saved_selection:
            if isinstance(saved_selection[0], dict):
                features_to_save = saved_selection
            else:
                features_to_save = [f for f in all_features if f.get("id") in saved_selection]
            print(f"[finalize_session] 📦 Using {len(features_to_save)} features already in session")

    # Fallback 2: SMART EXTRACTION from Questionnaire Answers
    # Many users select sections during the Q&A (Checkbox questions)
    if not features_to_save:
        print(f"[finalize_session] 🔍 Attempting Smart Extraction from Questionnaire...")
        answers = session.get("answers", {})
        for q_id, answer in answers.items():
            # If the answer is a list (checkbox) or string mentioning sections
            ans_str = str(answer).lower()
            for f in all_features:
                f_id = f.get("id", "").lower()
                f_name = f.get("name", "").lower()
                if f_id in ans_str or f_name in ans_str:
                    if f not in features_to_save:
                        features_to_save.append(f)
        
        # Always add Hero if we found anything else
        if features_to_save:
            hero = next((f for f in all_features if f.get("id") == "hero"), None)
            if hero and hero not in features_to_save:
                features_to_save.insert(0, hero)
            print(f"[finalize_session] ✨ Smart extracted {len(features_to_save)} features from answers")

    # Fallback 3: Last resort (Minimal set)
    if not features_to_save:
        features_to_save = [f for f in all_features if f.get("id") == "hero"]
        if not features_to_save and all_features:
            features_to_save = [all_features[0]]
        print(f"[finalize_session] ⚠️ No selection OR extraction found. Minimal set (1 page)")
    
    # Create metadata dictionary
    clean_session = session.copy()
    # PRESERVE 'answers' as it is critical for Blueprint generation context
    keys_to_remove = ["question_history", "asked_questions", "asked_topics"]
    for key in keys_to_remove:
        clean_session.pop(key, None)
    
    # CRITICAL: Sync both places
    clean_session["selected_features"] = features_to_save

    metadata = {
        "user_id": user_id,
        "session_id": session_id,
        "project_id": project_id,
        "timestamp": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "user_prompt": session.get("prompt", ""),
        "questionnaire": clean_session,
        "features": features_to_save,         # Main source for generator
        "selected_features": features_to_save, # Extra copy for safety
        "final_metadata_ready": True
    }


    db_record = save_metadata(
        metadata=metadata,
        user_id=str(user_id),
        username=username,
        project_id=project_id,
        session_id=session_id
    )
    delete_session(session_id)

    return {
        **metadata,
        **db_record,
    }


def answer_and_generate_next_question(user, session_id: str, question_id: str, answer: Any):
    # Extract user ID from User object
    user_id = user.user_id if hasattr(user, 'user_id') else user
    session = get_session(session_id)
    if not session:
        raise ValueError("Session not found.")

    if session["user_id"] != user_id:
        raise PermissionError("Unauthorized session.")

    if session.get("completed"):
        save_session(session_id, session)
        return None, len(session.get("question_history", [])), True

    # check if we are updating a previous question
    history = session.get("question_history", [])
    if not history:
        raise ValueError("No questions have been asked yet.")
    
    last_entry = history[-1]
    if last_entry["id"] != question_id:
        # Check if this question exists earlier in history
        if any(q["id"] == question_id for q in history):
            # This is an update to a previous answer
            return update_answer_and_regenerate(user, session_id, question_id, answer)
            
        # If not found at all, then it's a mismatch
        raise ValueError("Question order mismatch.")

    _record_answer(session, question_id, answer)
    next_question = _generate_next_question(session)
    
    # If the interview just completed, pre-generate recommended features
    if session.get("completed"):
        print(f"[RecommendationService] 🎉 Interview complete! Generating features for: {session.get('business_type')}")
        features = groq_service.generate_features(
            prompt=session.get("prompt"),
            business_type=session.get("business_type"),
            answers=session.get("answers", {})
        )
        session["features"] = features
        print(f"[RecommendationService] ✅ Generated {len(features)} template-proven features")

    save_session(session_id, session)

    total_asked = len(session.get("question_history", []))
    completed = session.get("completed", False)
    return next_question, total_asked, completed


def update_answer_and_regenerate(user, session_id: str, question_id: str, new_answer: Any):
    """
    Update a previously answered question and regenerate all subsequent questions.
    
    This function:
    1. Validates session ownership
    2. Finds the question by ID in history
    3. Updates the answer for that question
    4. Truncates all questions after the updated one
    5. Cleans up asked_questions and asked_topics
    6. Generates the next question based on new context
    7. Saves to Redis and returns
    """
    # Extract user ID from User object
    user_id = user.user_id if hasattr(user, 'user_id') else user
    session = get_session(session_id)
    if not session:
        raise ValueError("Session not found.")
    
    if session["user_id"] != user_id:
        raise PermissionError("Unauthorized session.")
    
    history = session.get("question_history", [])
    
    # Find the question index by ID
    question_index = None
    for idx, entry in enumerate(history):
        if entry.get("id") == question_id:
            question_index = idx
            break
    
    if question_index is None:
        raise ValueError(f"Question '{question_id}' not found in history.")
    
    # Update the answer for the target question
    target_question = history[question_index]
    question_type = (target_question.get("type") or "").strip().lower()
    
    if question_type == "checkbox":
        if isinstance(new_answer, str):
            parsed = [item.strip() for item in new_answer.split(",") if item.strip()]
        else:
            parsed = list(new_answer) if isinstance(new_answer, (list, tuple, set)) else [new_answer]
        target_question["answer"] = parsed
        session.setdefault("answers", {})[question_id] = parsed
    else:
        target_question["answer"] = new_answer
        session.setdefault("answers", {})[question_id] = new_answer
    
    # Handle color preferences if this is a color question
    if groq_service.is_color_question(target_question):
        if isinstance(target_question["answer"], (list, tuple, set)):
            stored = ", ".join(str(item) for item in target_question["answer"] if item)
        else:
            stored = str(target_question.get("answer") or "").strip()
        if stored:
            session["color_preferences"] = stored
    
    # Truncate all questions after this one
    truncated_history = history[:question_index + 1]
    session["question_history"] = truncated_history
    
    # Remove answers for truncated questions
    truncated_ids = {entry["id"] for entry in truncated_history}
    session["answers"] = {
        qid: ans for qid, ans in session.get("answers", {}).items()
        if qid in truncated_ids
    }
    
    # Rebuild asked_questions from remaining history
    session["asked_questions"] = []
    for entry in truncated_history:
        normalized = _normalize_question_text(entry.get("question"))
        if normalized and normalized not in session["asked_questions"]:
            session["asked_questions"].append(normalized)
        source_normalized = _normalize_question_text(entry.get("_source_question"))
        if source_normalized and source_normalized not in session["asked_questions"]:
            session["asked_questions"].append(source_normalized)
    
    # Rebuild asked_topics from remaining history
    session["asked_topics"] = []
    for entry in truncated_history:
        topic_label = groq_service.classify_question_topic(entry)
        if topic_label and topic_label not in session["asked_topics"]:
            session["asked_topics"].append(topic_label)
    
    # Also update questions list
    session["questions"] = session["questions"][:question_index + 1] if session.get("questions") else []
    
    # Mark session as not completed since we're regenerating
    session["completed"] = False
    
    # Generate the next question
    next_question = _generate_next_question(session)
    
    # Save the updated session
    save_session(session_id, session)
    
    total_asked = len(session.get("question_history", []))
    completed = session.get("completed", False)
    return next_question, total_asked, completed



def _record_answer(session: Dict[str, Any], question_id: str, answer: Any):
    history = session.get("question_history", [])
    if not history:
        raise ValueError("No questions have been asked yet.")

    last_entry = history[-1]
    if last_entry["id"] != question_id:
        raise ValueError("Question order mismatch.")

    question_type = (last_entry.get("type") or "").strip().lower()
    if question_type == "checkbox":
        if isinstance(answer, str):
            parsed = [item.strip() for item in answer.split(",") if item.strip()]
        else:
            parsed = list(answer) if isinstance(answer, (list, tuple, set)) else [answer]
        last_entry["answer"] = parsed
        session.setdefault("answers", {})[question_id] = parsed
    else:
        last_entry["answer"] = answer
        session.setdefault("answers", {})[question_id] = answer

    if groq_service.is_color_question(last_entry):
        if isinstance(last_entry["answer"], (list, tuple, set)):
            stored = ", ".join(str(item) for item in last_entry["answer"] if item)
        else:
            stored = str(last_entry.get("answer") or "").strip()
        if stored:
            session["color_preferences"] = stored


def _generate_next_question(session: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """
    Generate the next question using Template-Based Question Generator.
    
    This ensures:
    1. Questions are relevant to the website type's templates
    2. Every question maps to actual template props
    3. Questions have variety (different wording each time)
    4. Websites are unique based on user answers
    """
    if session.get("completed"):
        return None

    max_questions = session.get("max_questions") or MAX_QUESTIONS
    history = session.setdefault("question_history", [])
    next_index = len(history) + 1

    if next_index > max_questions:
        session["completed"] = True
        return None

    # Get or create the question generator for this session
    generator = _get_or_create_generator(session)
    
    # Get previous answers for context
    answers = session.get("answers", {})
    
    # Generate the next question using template-based generator
    question = generator.generate_single_question(
        question_index=next_index,
        previous_answers=answers
    )
    
    # Fallback to AI-generated question if template generator returns None
    if not question:
        # Use groq_service as fallback for edge cases
        detected_business_type = session.get("business_type", "Business")
        asked_normalized = session.setdefault("asked_questions", [])
        disallowed_questions = set(asked_normalized)
        asked_topics = session.setdefault("asked_topics", [])
        disallowed_topics = set(asked_topics)
        
        question = groq_service.generate_last_chance_question(
            prompt=session["prompt"],
            language=session["language"],
            business_type=detected_business_type,
            next_index=next_index,
            disallowed_questions=disallowed_questions,
            color_question_needed=False,
            business_name_needed=False,
        )
        
        if not question:
            session["completed"] = True
            return None

    # Add to history
    history.append(
        {
            "id": question["id"],
            "question": question["question"],
            "type": question.get("type"),
            "options": question.get("options"),
            "prop_key": question.get("prop_key"),  # Important: maps to template props
            "section": question.get("section"),
            "_source_question": question.get("_source_question"),
            "_topic_label": question.get("_topic_label", question.get("section")),
            "answer": "",
        }
    )
    
    session.setdefault("questions", []).append(question)
    
    # Track asked questions
    asked_normalized = session.setdefault("asked_questions", [])
    normalized = _normalize_question_text(question.get("question"))
    if normalized and normalized not in asked_normalized:
        asked_normalized.append(normalized)
    
    asked_topics = session.setdefault("asked_topics", [])
    topic_label = question.get("section") or question.get("_topic_label")
    if topic_label and topic_label not in asked_topics:
        asked_topics.append(topic_label)
    
    # Track asked prop_keys for generator persistence
    prop_key = question.get("prop_key")
    if prop_key:
        asked_props = session.setdefault("_generator_asked_props", [])
        if prop_key not in asked_props:
            asked_props.append(prop_key)
    
    session["completed"] = len(history) >= max_questions
    return question


def _get_or_create_generator(session: Dict[str, Any]) -> TemplateQuestionGenerator:
    """
    Get or create a TemplateQuestionGenerator for the session.
    Stores generator state in session for consistency.
    """
    # Check if we already have generator state
    generator_state = session.get("_generator_asked_props", set())
    
    # Detect/update business type
    answers = session.get("answers", {})
    detected_type = groq_service.infer_business_type_from_answers(
        session.get("prompt", ""),
        answers,
        session.get("business_type", "Business"),
    )
    session["business_type"] = detected_type
    
    # Map business type to template type
    template_type = _map_to_template_type(detected_type)
    
    # Create generator
    generator = TemplateQuestionGenerator(
        website_type=template_type,
        language=session.get("language", "English")
    )
    
    # Restore previously asked props
    if isinstance(generator_state, (list, set)):
        generator.asked_props = set(generator_state)
    
    return generator


def _map_to_template_type(business_type: str) -> str:
    """
    Map detected business type to template directory name.
    """
    type_lower = business_type.lower()
    
    mappings = {
        # Cafe/Coffee
        "cafe": "cafe",
        "coffee": "cafe",
        "bakery": "cafe",
        "coffee shop": "cafe",
        
        # Restaurant
        "restaurant": "restaurant",
        "dining": "restaurant",
        "food": "restaurant",
        "bistro": "restaurant",
        "bar": "restaurant",
        
        # Gaming
        "gaming": "gaming",
        "esports": "gaming",
        "game": "gaming",
        "streamer": "gaming",
        
        # Portfolio
        "portfolio": "portfolio",
        "personal": "portfolio",
        "freelancer": "portfolio",
        "developer": "portfolio",
        "designer": "portfolio",
        
        # Agency
        "agency": "agency",
        "business": "agency",
        "corporate": "agency",
        "company": "agency",
        "consulting": "agency",
        "marketing": "agency",
        
        # Ecommerce
        "ecommerce": "ecommerce",
        "e-commerce": "ecommerce",
        "shop": "ecommerce",
        "store": "ecommerce",
        "retail": "ecommerce",
        
        # Movie
        "movie": "movie",
        "cinema": "movie",
        "theater": "movie",
        "theatre": "movie",
        "film": "movie",
    }
    
    # Find matching template type
    for keyword, template_type in mappings.items():
        if keyword in type_lower:
            return template_type
    
    # Default to agency for unknown types
    return "agency"

